export const initialFormData = {
  patientInitials: "",
  dateOfBirth: "",
  sex: "",
  ageAtOnset: "",
  email: "",
  phoneNumber: "",
  typeofcustomer: "",
  reactionStartDate: "",
  reactionDescription: "",
  reactionOutcome: "",
  actionTaken: "",
  labResults: "",
  seriousness: "",
  suspectedDrugName: "",
  batchNumber: "",
  manufactureExpiryDate: "",
  dailyDose: "",
  routeOfAdministration: "",
  indication: "",
  drugStartDate: "",
  lastAdministrationDate: "",
  duration: "",
  rechallenge: "",
  concomitantDrugName: "",
  concomitantStartDate: "",
  concomitantLastAdministration: "",
  medicalHistory: "",
  medicalHistoryOther:"",
  caseSource: "",
  previousCaseIdentifiers: "",
  recentInformationDate: "",
  reportTypes: "",
};

export const requiredFields = {
  patientInitials: "Enter the patient name.",
  reactionStartDate: "Enter the date the reaction started.",
  reactionDescription: "Describe the reaction.",
  reactionOutcome: "Enter the observed outcome.",
  suspectedDrugName: "Enter the suspected drug name.",
};
